### ISSUE TITLE
Write the two sec-ai Welcome Guides (for users and contributors)

### ISSUE THREAD

**Issue by alphanome** [alphanome-ai/sec-ai#8]
We need to create two one-pager documentation that provides a comprehensive introduction to sec-parser for newcomers. This document should serve as a quick guide to understanding the project, its structure, algorithm design, domain context, and contribution guidelines.

**Comment by Elijas** [comment]
Hello,

This issue is being closed as it's not something we plan to work on in the immediate future. We've consolidated our roadmap and future plans in a centralized location to provide a clear and structured overview of our project's direction.

For anyone visiting this issue in the future, please refer to our roadmap and future plans discussion at [this link](https://github.com/orgs/alphanome-ai/discussions/categories/roadmap-future-plans) for more information.

Thank you for your understanding.

Best,
Elijas
